"""Golden-vector generator for the mr_fft_chain / mr_fft_top datapath.

Chains per-stage models in the EXACT configuration proven bit-exact by the
stage golden flow (stage_ref.py): octant-ROM twiddles, stage_index 0,
"18 bits in memory, wide in flight" (s18/16 data, s18/16 coeff/twiddle,
half_up, exit_round, internal_frac 22), FIXED per-radix scaling. A config's
active stages are its ascending radix factorization [2..][3..][5..] with
progressively divided sub-sizes -- exactly what the RTL's c_slot_cfgs places
onto the slots; bypassed slots are value-neutral so they need no model.

Per config: 2 data frames (ramp + seeded random) + 1 zero flush frame in,
expected = model output stream [latency : latency + 2N] as raw codes.

Vectors are written as a plain CSV data file read by the TB at runtime with
textio (NOT a VHDL constant package: xsim 2022.2's debug database chokes on
very large package constants, and a data file needs no HDL recompile).

Regenerate:  .venv/bin/python model/chain_ref.py
Consumed by: rtl/tb/tb_mr_fft_top.vhd  (reads rtl/tb/chain_vectors.csv)
"""
import argparse

import numpy as np

from mixed_radix_fft_fxp import (MixedRadix_FinalScaler_FXP,
                                 MixedRadix_SDF_stage_counter_ctrl_FXP)

SCALE_FRAC = 21   # c_scale_frac in mr_fft_pkg.vhd (s4.21 scaler constants)

# small configs that still cover: multiple radix-2 slots, the radix23 region,
# one and two radix-5 slots, and mid-pipeline bypass gaps between the regions
DEFAULT_SIZES = [12, 24, 60, 120, 300]
N_FRAMES = 2


def factorize_ascending(n):
    radices, rem = [], n
    for r in (2, 3, 5):
        while rem % r == 0:
            radices.append(r)
            rem //= r
    if rem != 1:
        raise ValueError(f'N={n} is not 2^a*3^b*5^c')
    return radices


def to_code(value, frac_w):
    code = round(value * 2.0 ** frac_w)
    assert code == value * 2.0 ** frac_w, f'non-exact code for {value}'
    return int(code)


def input_codes(size, word_w, rng):
    """Like stage_ref: ramp frame, seeded-random frame (within +-2**(w-4) so
    levels stay comfortably inside the input contract), zero flush frame."""
    ramp = [(64 * (k + 1), -32 * (k + 1)) for k in range(size)]
    lim = 2 ** (word_w - 4)
    rand = [(int(rng.integers(-lim, lim)), int(rng.integers(-lim, lim)))
            for _ in range(size)]
    return ramp + rand + [(0, 0)] * size


def run_cfg(n, codes, data_dtype, coeff_dtype, twiddle_dtype, frac_w):
    radices = factorize_ascending(n)
    sizes, acc = [], 1
    for r in radices:
        sizes.append(n // acc)
        acc *= r

    stages = [
        MixedRadix_SDF_stage_counter_ctrl_FXP(
            config=r, stage_index=0, size=s, cfg_delay=s // r,
            dtype=data_dtype, coeff_dtype=coeff_dtype, preadder_shift_bits=None,
            overflow='wrap', rounding='half_up', capability=r,
            twiddle_source='octant', twiddle_dtype=twiddle_dtype,
            preadder_exit_round=True, preadder_internal_frac=22)
        for r, s in zip(radices, sizes)
    ]
    # final scaler (mr_fft_scaler): x 2**total_shift/N with the quantized
    # u2.<SCALE_FRAC> constant -- the top's output is the X/N convention
    total_shift = sum({2: 1, 3: 2, 5: 3}[r] for r in radices)
    scaler = MixedRadix_FinalScaler_FXP(
        size=n, total_shift=total_shift, dtype=data_dtype,
        output_dtype=data_dtype, rounding='half_up', overflow='wrap',
        quantized_scale_frac=SCALE_FRAC)

    scale = 2.0 ** frac_w
    out = []
    for (re, im) in codes:
        y = complex(re / scale, im / scale)
        for st in stages:
            y = st.calculate(y)
        y = scaler.scale_sample(y)
        out.append((to_code(y.real, frac_w), to_code(y.imag, frac_w)))

    lat = sum((r - 1) * (s // r) for r, s in zip(radices, sizes))
    return out[lat:lat + N_FRAMES * n]


def emit_csv(cfgs, word_w, frac_w):
    L = [
        "# AUTO-GENERATED by model/chain_ref.py -- do not edit by hand.",
        f"# data format: sfixed({word_w - frac_w - 1} downto -{frac_w})"
        f"  ({word_w} b/component), integer codes",
        "# layout: num_cfgs line; then per config one 'N,n_in,n_exp' header,",
        "#         n_in input 're,im' rows, n_exp expected 're,im' rows",
        str(len(cfgs)),
    ]
    for c in cfgs:
        L.append(f"{c['n']},{len(c['cin'])},{len(c['exp'])}")
        L.extend(f"{re},{im}" for re, im in c['cin'])
        L.extend(f"{re},{im}" for re, im in c['exp'])
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--int", type=int, default=2, help="c_fxp_int_width (default 2)")
    ap.add_argument("--frac", type=int, default=16, help="c_fxp_frac_width (default 16)")
    ap.add_argument("--coeff-int", type=int, default=2)
    ap.add_argument("--coeff-frac", type=int, default=16)
    ap.add_argument("--sizes", type=int, nargs="+", default=DEFAULT_SIZES)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--csv", default="rtl/tb/chain_vectors.csv")
    a = ap.parse_args()

    word_w = a.int + a.frac
    data_dtype = f"fxp-s{word_w}/{a.frac}"
    coeff_dtype = f"fxp-s{a.coeff_int + a.coeff_frac}/{a.coeff_frac}"
    twiddle_dtype = coeff_dtype

    rng = np.random.default_rng(a.seed)
    cfgs = []
    for n in a.sizes:
        cin = input_codes(n, word_w, rng)
        exp = run_cfg(n, cin, data_dtype, coeff_dtype, twiddle_dtype, a.frac)
        cfgs.append(dict(n=n, cin=cin, exp=exp))
        print(f"N={n:4d}: radices {factorize_ascending(n)}, "
              f"{len(cin)} in / {len(exp)} expected")

    with open(a.csv, "w") as f:
        f.write(emit_csv(cfgs, word_w, a.frac))
    print(f"wrote {len(cfgs)} configs -> {a.csv}")
