"""Golden-vector generator for rtl/src/mr_fft_preadder.vhd.

Runs MixedRadix_PreAdder_FXP with the RTL's fixed-point conventions
(data s17/12, coeff s18/16, wrap overflow, floor rounding — one dtype for
ports and datapath, matching mr_fft_pkg.vhd where wide == data format) and
emits a self-checking VHDL package of raw two's-complement integer codes.

Regenerate:  python model/preadder_ref.py
Consumed by: rtl/tb/tb_mr_fft_preadder_gen.vhd
"""
import argparse

import numpy as np

from mixed_radix_fft_fxp import MixedRadix_PreAdder_FXP

# (G_CAPABILITY, s0, s1, model capability, valid complex outputs)
CONFIGS = [
    (2, 0, 0, 5, 5),   # radix235 hw, radix-2 mode
    (2, 1, 0, 5, 5),   # radix235 hw, radix-3 mode
    (2, 2, 1, 5, 5),   # radix235 hw, radix-5 mode
    (1, 0, 0, 3, 3),   # radix23  hw, radix-2 mode
    (1, 1, 0, 3, 3),   # radix23  hw, radix-3 mode
    (0, 0, 0, 2, 2),   # radix2   hw
]


def corner_codes(word_w):
    hi = 2 ** (word_w - 1) - 1
    lo = -2 ** (word_w - 1)
    alt = int("01" * (word_w // 2), 2)              # 0101... pattern
    return [0, 1, -1, hi, lo, hi // 2, lo // 2, alt, -alt]


def corner_vectors(word_w):
    """Each vector is 10 codes: x0.re, x0.im, ..., x4.re, x4.im."""
    corners = corner_codes(word_w)
    vecs = [[c] * 10 for c in corners]              # all components equal
    vecs.append([corners[i % len(corners)] for i in range(10)])   # mixed
    vecs.append([corners[(i + 3) % len(corners)] for i in range(10)])
    return vecs


def run_model(cap, s0, s1, codes, data_dtype, coeff_dtype, frac_w):
    pre = MixedRadix_PreAdder_FXP(dtype=data_dtype, shift_bits=0,
                                  overflow='wrap', coeff_dtype=coeff_dtype,
                                  rounding='around', capability=cap)
    scale = 2.0 ** frac_w
    n_in = {5: 5, 3: 3, 2: 2}[cap]
    for i in range(n_in):
        setattr(pre, f'input_{i}',
                complex(codes[2 * i] / scale, codes[2 * i + 1] / scale))
    pre.calculate(s0=s0, s1=s1)
    out = [0] * 10
    n_out = {5: 5, 3: 3, 2: 2}[cap]
    for i in range(n_out):
        v = getattr(pre, f'output_{i}')
        out[2 * i] = to_code(v.real, frac_w)
        out[2 * i + 1] = to_code(v.imag, frac_w)
    return out


def to_code(value, frac_w):
    code = round(value * 2.0 ** frac_w)
    assert code == value * 2.0 ** frac_w, f'non-exact code for {value}'
    return int(code)


def coeff_expectations(data_dtype, coeff_dtype, coeff_frac):
    pre = MixedRadix_PreAdder_FXP(dtype=data_dtype, coeff_dtype=coeff_dtype,
                                  overflow='wrap', rounding='around', capability=5)
    return {
        'EXP_K2_RE': to_code(pre.k2, coeff_frac),
        'EXP_K3_IM': to_code(pre.k3.imag, coeff_frac),
        'EXP_K4_IM': to_code(pre.k4.imag, coeff_frac),
        'EXP_K5_IM': to_code(pre.k5.imag, coeff_frac),
        'EXP_K6_RE': to_code(pre.k6, coeff_frac),
    }


def build_vectors(seed, nrand, word_w, data_dtype, coeff_dtype, frac_w):
    rng = np.random.default_rng(seed)
    tests = []
    for g_cap, s0, s1, cap, n_out in CONFIGS:
        stims = corner_vectors(word_w)
        stims += [list(rng.integers(-2 ** (word_w - 1), 2 ** (word_w - 1),
                                    size=10)) for _ in range(nrand)]
        for codes in stims:
            codes = [int(c) for c in codes]
            exp = run_model(cap, s0, s1, codes, data_dtype, coeff_dtype, frac_w)
            tests.append((g_cap, s0, s1, n_out, codes, exp))
    return tests


def emit_vhdl_pkg(tests, consts, word_w, frac_w):
    lines = []
    lines.append("-- AUTO-GENERATED by model/preadder_ref.py -- do not edit by hand.")
    lines.append(f"-- data format: sfixed({word_w - frac_w - 1} downto -{frac_w})"
                 f"  ({word_w} b/component), wrap + truncate")
    lines.append("package preadder_vectors_pkg is")
    for name, val in consts.items():
        lines.append(f"    constant {name} : integer := {val};")
    lines.append("    type t_codes is array (0 to 9) of integer;")
    lines.append("    type t_pv is record")
    lines.append("        cap    : integer;  -- G_CAPABILITY (2/1/0)")
    lines.append("        s0, s1 : integer;")
    lines.append("        nout   : integer;  -- valid complex outputs")
    lines.append("        x      : t_codes;  -- inputs  x0.re, x0.im, ... x4.im")
    lines.append("        e      : t_codes;  -- expected X0.re, X0.im, ... X4.im")
    lines.append("    end record;")
    lines.append("    type t_pv_arr is array (natural range <>) of t_pv;")
    lines.append("    constant TESTS : t_pv_arr := (")
    body = []
    for (cap, s0, s1, n_out, x, e) in tests:
        xs = ", ".join(f"{v:>7}" for v in x)
        es = ", ".join(f"{v:>7}" for v in e)
        body.append(f"        ({cap}, {s0}, {s1}, {n_out},\n"
                    f"         ({xs}),\n"
                    f"         ({es}))")
    lines.append(",\n".join(body))
    lines.append("    );")
    lines.append("end package;")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--int", type=int, default=5, help="c_fxp_int_width (default 5)")
    ap.add_argument("--frac", type=int, default=12, help="c_fxp_frac_width (default 12)")
    ap.add_argument("--coeff-int", type=int, default=2, help="c_coeff_int_width (default 2)")
    ap.add_argument("--coeff-frac", type=int, default=16, help="c_coeff_frac_width (default 16)")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--nrand", type=int, default=40, help="random vectors per config")
    ap.add_argument("--vhdl", default="rtl/tb/preadder_vectors_pkg.vhd")
    a = ap.parse_args()

    word_w = a.int + a.frac
    data_dtype = f"fxp-s{word_w}/{a.frac}"
    coeff_dtype = f"fxp-s{a.coeff_int + a.coeff_frac}/{a.coeff_frac}"

    consts = coeff_expectations(data_dtype, coeff_dtype, a.coeff_frac)
    tests = build_vectors(a.seed, a.nrand, word_w, data_dtype, coeff_dtype, a.frac)

    with open(a.vhdl, "w") as f:
        f.write(emit_vhdl_pkg(tests, consts, word_w, a.frac))
    print(f"wrote {len(tests)} vectors -> {a.vhdl}")
    for name, val in consts.items():
        print(f"  {name} = {val}")
