-- AUTO-GENERATED by model/stage_ref.py --cap 0 -- do not edit by hand.
-- data format: sfixed(4 downto -13)  (18 b/component), wrap + round-to-nearest
-- Streams are interleaved integer codes: re0, im0, re1, im1, ...
package stage_vectors_cap0_pkg is
    type t_int_arr is array (natural range <>) of integer;
    constant NUM_CFGS : integer := 3;
    constant CFG_RADIX : t_int_arr := (2, 2, 2);
    constant CFG_SIZE : t_int_arr := (8, 4, 2);
    -- model call index of the first valid output (= size - delay)
    constant CFG_VALID_START : t_int_arr := (4, 2, 1);
    -- slices of IN_CODES / EXP_CODES per config: [ofs(i), ofs(i+1))
    constant CFG_IN_OFS : t_int_arr := (0, 48, 72, 84);
    constant CFG_EXP_OFS : t_int_arr := (0, 32, 48, 56);
    constant IN_CODES : t_int_arr := (
             64,     -32,     128,     -64,     192,     -96,     256,    -128,
            320,    -160,     384,    -192,     448,    -224,     512,    -256,
           -879,     387,    8361,   14760,  -15242,  -11661,   10582,   14701,
          -8218,   -6166,   12092,   -2513,   -7433,   10738,   -7963,   -2976,
              0,       0,       0,       0,       0,       0,       0,       0,
              0,       0,       0,       0,       0,       0,       0,       0,
             64,     -32,     128,     -64,     192,     -96,     256,    -128,
           4712,    1625,  -13575,  -15481,   11979,    8307,   11071,    1249,
              0,       0,       0,       0,       0,       0,       0,       0,
             64,     -32,     128,     -64,   10405,   -5580,   -1551,    9451,
              0,       0,       0,       0
    );
    constant EXP_CODES : t_int_arr := (
            384,    -192,     512,    -256,     640,    -320,     768,    -384,
           -256,     128,    -256,     128,    -256,     128,    -256,     128,
          -9097,   -5779,   20453,   12247,  -22675,    -923,    2619,   11725,
           7339,    6553,   -3731,   17273,   -7809,  -22399,   18545,   17677,
            256,    -128,     384,    -192,    -128,      64,    -128,      64,
          16691,    9932,   -2504,  -14232,   -7267,   -6682,  -24646,  -16730,
            192,     -96,     -64,      32,    8854,    3871,   11956,  -15031
    );
end package;
