-- AUTO-GENERATED by model/stage_ref.py --cap 0 -- do not edit by hand.
-- data format: sfixed(4 downto -13)  (18 b/component), wrap + round-to-nearest
-- Streams are interleaved integer codes: re0, im0, re1, im1, ...
package stage_vectors_cap0_pkg is
    type t_int_arr is array (natural range <>) of integer;
    constant NUM_CFGS : integer := 3;
    constant CFG_RADIX : t_int_arr := (2, 2, 2);
    constant CFG_SIZE : t_int_arr := (8, 2, 4);
    -- model call index of the first valid output (= size - delay)
    constant CFG_VALID_START : t_int_arr := (4, 1, 2);
    -- slices of IN_CODES / EXP_CODES per config: [ofs(i), ofs(i+1))
    constant CFG_IN_OFS : t_int_arr := (0, 48, 60, 84);
    constant CFG_EXP_OFS : t_int_arr := (0, 32, 40, 56);
    constant IN_CODES : t_int_arr := (
             64,     -32,     128,     -64,     192,     -96,     256,    -128,
            320,    -160,     384,    -192,     448,    -224,     512,    -256,
           -879,     387,    8361,   14760,  -15242,  -11661,   10582,   14701,
          -8218,   -6166,   12092,   -2513,   -7433,   10738,   -7963,   -2976,
              0,       0,       0,       0,       0,       0,       0,       0,
              0,       0,       0,       0,       0,       0,       0,       0,
             64,     -32,     128,     -64,    4712,    1625,  -13575,  -15481,
              0,       0,       0,       0,
             64,     -32,     128,     -64,     192,     -96,     256,    -128,
          11979,    8307,   11071,    1249,   10405,   -5580,   -1551,    9451,
              0,       0,       0,       0,       0,       0,       0,       0
    );
    constant EXP_CODES : t_int_arr := (
            384,    -192,     512,    -256,     640,    -320,     768,    -384,
           -256,     128,     -91,     272,     128,     256,     272,      91,
          -9097,   -5779,   20453,   12247,  -22675,    -923,    2619,   11725,
           7339,    6553,    9576,   14852,  -22399,    7809,    -614,  -25613,
            192,     -96,     -64,      32,   -8863,  -13856,   18287,   17106,
            256,    -128,     384,    -192,    -128,      64,      64,     128,
          22384,    2727,    9520,   10700,    1574,   13887,   -8202,  -12622
    );
end package;
