library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

library work;
use work.mr_fft_pkg.all;
use work.stage_vectors_pkg.all;   -- generated by model/stage_ref.py

-- Self-checking mr_fft_stage TB driven by generated golden vectors.
-- Regenerate vectors:  python model/stage_ref.py
--
-- G_CAPABILITY=2 (radix235). Exercises:
--   * decoupled ready/valid handshakes: i_valid and i_ready are toggled with
--     independent pseudo-random gaps, so the input side runs ahead into the
--     FIFOs while the output side stalls (and vice versa). While i_valid is
--     low a junk sample is driven to catch any accidental consumption.
--   * reconfiguration in ARBITRARY order WITHOUT reset (single reset at time
--     0 only): once a config's frames are fed and its outputs fully drained,
--     the stage is back in its reset-equivalent state (counters wrapped,
--     pending clear, FIFOs empty), so the next config is simply applied and
--     streaming resumes.
--
-- Per config: stream the input codes (one per accepted beat), capture
-- o_sample on every output beat (o_valid and i_ready), then drain the
-- remaining stored results with i_valid low -- once drained, output beats =
-- input beats (conservation). The captured stream is compared beat-for-beat
-- against the expected codes: the first valid output must be EXP(0), so
-- o_valid timing errors show up as data mismatches. Raw two's-complement
-- codes are compared so any mismatch is a real bit difference.
entity tb_mr_fft_stage is end entity;

architecture sim of tb_mr_fft_stage is
  constant CFGS : t_config_arr := ((2, 8), (2, 2), (5, 20), (2, 4), (3, 12), (5, 5));

  constant CLK_PERIOD : time    := 10 ns;
  constant C_MAX_CAP  : integer := 128;  -- capture buffer size (>= n_in)
  constant C_MAX_MSG  : integer := 5;    -- mismatch reports per config

  subtype t_word is std_logic_vector(c_fxp_word_width - 1 downto 0);
  type t_cap_arr is array (0 to C_MAX_CAP - 1) of t_word;

  constant C_ZERO : t_cmplx := (re => (others => '0'), im => (others => '0'));

  signal clk      : std_logic := '0';
  signal reset    : std_logic := '1';
  signal cfg      : t_config  := CFGS(0);
  signal cfg_sel  : std_logic_vector(clogb2(CFGS'length) - 1 downto 0) := (others => '0');
  -- runtime delay = size/radix; wraps to 0 when it equals 2**width (the DUT's
  -- modular compares handle the wrapped code)
  signal cfg_delay : std_logic_vector(clogb2(get_delay_cnt(CFGS)) - 1 downto 0) := (others => '0');
  signal i_sample : t_cmplx   := C_ZERO;
  signal in_valid : std_logic := '0';
  signal in_ready : std_logic;
  signal o_sample : t_cmplx;
  signal out_valid : std_logic;
  signal out_ready : std_logic := '0';
  signal done     : boolean   := false;

  function to_fx(code : integer) return sfixed is
  begin
    return to_sfixed(std_logic_vector(to_signed(code, c_fxp_word_width)),
                     c_fxp_int_width - 1, -c_fxp_frac_width);
  end function;

  function code_slv(code : integer) return t_word is
  begin
    return std_logic_vector(to_signed(code, c_fxp_word_width));
  end function;

  function slv_image(w : t_word) return string is
  begin
    if is_x(w) then
      return "0x" & to_hstring(w) & " (metavalue)";
    end if;
    return integer'image(to_integer(signed(w)));
  end function;

  -- small LCG (Lehmer, modulus 65537) -- values stay well inside integer range
  function lcg(r : integer) return integer is
  begin
    return (r * 75 + 74) mod 65537;
  end function;

begin

  dut : entity work.mr_fft_stage
    generic map (G_CAPABILITY => 2, G_CONFIGS => CFGS)
    port map (
      i_clk    => clk,
      i_reset  => reset,
      i_config => cfg,
      i_config_sel => cfg_sel,
      i_config_delay => cfg_delay,
      i_sample => i_sample,
      i_valid  => in_valid,
      o_ready  => in_ready,
      o_sample => o_sample,
      o_valid  => out_valid,
      i_ready  => out_ready);

  clk <= not clk after CLK_PERIOD / 2 when not done else '0';

  check : process
    variable cap_re, cap_im : t_cap_arr;
    variable n_in, n_exp, vstart, in_ofs, exp_ofs : integer;
    variable in_idx, cap_cnt, guard : integer;
    variable rnd_v : integer := 12345;   -- LCG state for i_valid gaps
    variable rnd_r : integer := 54321;   -- LCG state for i_ready gaps
    variable v : boolean;
    variable errs, msgs : integer;
    variable exp_re, exp_im : t_word;
    variable pass_all : boolean := true;
  begin
    -- single reset at time 0; every later config is applied on the fly
    reset <= '1';
    in_valid <= '0';
    out_ready <= '0';
    for i in 0 to 3 loop
      wait until rising_edge(clk);
    end loop;
    reset <= '0';

    for c in 0 to NUM_CFGS - 1 loop
      n_in    := (CFG_IN_OFS(c + 1) - CFG_IN_OFS(c)) / 2;
      n_exp   := (CFG_EXP_OFS(c + 1) - CFG_EXP_OFS(c)) / 2;
      vstart  := CFG_VALID_START(c);
      in_ofs  := CFG_IN_OFS(c);
      exp_ofs := CFG_EXP_OFS(c);

      -- reconfigure on the fly: the previous config is fully drained, so the
      -- stage is in its reset-equivalent state -- just apply the new config
      wait until rising_edge(clk);
      cfg   <= (radix => CFG_RADIX(c), size => CFG_SIZE(c));
      cfg_sel <= std_logic_vector(to_unsigned(c, cfg_sel'length));
      cfg_delay <= std_logic_vector(to_unsigned(
          (CFG_SIZE(c) / CFG_RADIX(c)) mod 2**cfg_delay'length, cfg_delay'length));
      in_valid <= '0';
      out_ready <= '0';

      -- stream all n_in samples through the handshake with random gaps on
      -- both sides; capture on every output beat (out_valid and out_ready)
      in_idx  := 0;
      cap_cnt := 0;
      guard   := 0;
      while in_idx < n_in loop
        -- drive this cycle's stimulus just after the rising edge
        rnd_v := lcg(rnd_v);
        rnd_r := lcg(rnd_r);
        v := (rnd_v mod 4) /= 0;                    -- ~75% input valid
        out_ready <= '1' when (rnd_r mod 4) /= 0 else '0';   -- ~75% ready
        if v then
          in_valid <= '1';
          i_sample.re <= to_fx(IN_CODES(in_ofs + 2 * in_idx));
          i_sample.im <= to_fx(IN_CODES(in_ofs + 2 * in_idx + 1));
        else
          in_valid <= '0';
          i_sample.re <= to_fx(21845);              -- junk while not valid
          i_sample.im <= to_fx(-21846);
        end if;

        -- let the combinational handshake settle, then evaluate the beat
        wait until falling_edge(clk);
        if out_valid = '1' and out_ready = '1' then
          cap_re(cap_cnt) := to_slv(o_sample.re);
          cap_im(cap_cnt) := to_slv(o_sample.im);
          cap_cnt := cap_cnt + 1;
        end if;
        if v and in_ready = '1' then
          in_idx := in_idx + 1;
        end if;

        guard := guard + 1;
        assert guard < 50 * n_in
          report "handshake deadlock: no progress" severity failure;
        wait until rising_edge(clk);
      end loop;

      -- inputs done (whole frames): drain the remaining stored results with
      -- i_valid low; conservation demands exactly n_in output beats in total
      in_valid <= '0';
      i_sample.re <= to_fx(21845);
      i_sample.im <= to_fx(-21846);
      while cap_cnt < n_in loop
        rnd_r := lcg(rnd_r);
        out_ready <= '1' when (rnd_r mod 4) /= 0 else '0';
        wait until falling_edge(clk);
        if out_valid = '1' and out_ready = '1' then
          cap_re(cap_cnt) := to_slv(o_sample.re);
          cap_im(cap_cnt) := to_slv(o_sample.im);
          cap_cnt := cap_cnt + 1;
        end if;
        guard := guard + 1;
        assert guard < 50 * n_in
          report "drain deadlock: outputs missing (got " &
                 integer'image(cap_cnt) & "/" & integer'image(n_in) & ")"
          severity failure;
        wait until rising_edge(clk);
      end loop;
      out_ready <= '0';

      errs := 0;
      msgs := 0;
      for k in 0 to n_exp - 1 loop
        exp_re := code_slv(EXP_CODES(exp_ofs + 2 * k));
        exp_im := code_slv(EXP_CODES(exp_ofs + 2 * k + 1));
        if k >= cap_cnt or cap_re(k) /= exp_re or cap_im(k) /= exp_im then
          errs := errs + 1;
          if msgs < C_MAX_MSG then
            report "  out beat " & integer'image(k) & " got (" &
                   slv_image(cap_re(k)) & "," & slv_image(cap_im(k)) &
                   ") exp (" & integer'image(EXP_CODES(exp_ofs + 2 * k)) & "," &
                   integer'image(EXP_CODES(exp_ofs + 2 * k + 1)) & ")"
              severity error;
            msgs := msgs + 1;
          end if;
        end if;
      end loop;

      if errs = 0 then
        report "config radix=" & integer'image(CFG_RADIX(c)) &
               " N=" & integer'image(CFG_SIZE(c)) &
               ": PASS -- " & integer'image(n_exp) &
               " samples match (" & integer'image(cap_cnt) &
               " output beats drained)"
          severity note;
      else
        pass_all := false;
        report "config radix=" & integer'image(CFG_RADIX(c)) &
               " N=" & integer'image(CFG_SIZE(c)) &
               ": FAIL -- " & integer'image(errs) & "/" &
               integer'image(n_exp) & " sample mismatches"
          severity error;
      end if;
    end loop;

    if pass_all then
      report "TB PASS -- mr_fft_stage matches the Python golden model for all configs"
        severity note;
    else
      report "TB FAIL -- mr_fft_stage does not match the Python golden model"
        severity failure;
    end if;
    done <= true;
    wait;
  end process check;

end architecture sim;
