library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

library work;
use work.mr_fft_pkg.all;
use work.stage_vectors_cap0_pkg.all;   -- generated by model/stage_ref.py --cap 0

-- Self-checking mr_fft_stage TB driven by generated golden vectors.
-- Regenerate vectors:  python model/stage_ref.py --cap 0
--
-- G_CAPABILITY=0 (radix2): radix 2 at delay 4 and at
-- delay 2 (runtime delay < physical FIFO depth). The runtime delay
-- (size/radix) is driven on i_config_delay per config.
--
-- Per config: reset, stream the input codes one per clock, capture o_sample
-- every clock, then compare the expected stream (model call index
-- CFG_VALID_START onward) against the capture at every candidate latency
-- 0..C_MAX_LAT. The stage is a fixed-latency stream pipe, so a correct DUT
-- matches the whole expected stream at exactly one offset. Raw
-- two's-complement codes are compared so any mismatch is a real bit difference.
entity tb_mr_fft_stage_cap0 is end entity;

architecture sim of tb_mr_fft_stage_cap0 is
  constant CFGS : t_config_arr := ((2, 8), (2, 4), (2, 2));

  constant CLK_PERIOD : time    := 10 ns;
  constant C_MAX_LAT  : integer := 8;    -- latency alignment search window
  constant C_MAX_CAP  : integer := 128;  -- capture buffer size (>= n_in + C_MAX_LAT)
  constant C_MAX_MSG  : integer := 5;    -- mismatch reports per config

  subtype t_word is std_logic_vector(c_fxp_word_width - 1 downto 0);
  type t_cap_arr is array (0 to C_MAX_CAP - 1) of t_word;

  constant C_ZERO : t_cmplx := (re => (others => '0'), im => (others => '0'));

  signal clk      : std_logic := '0';
  signal reset    : std_logic := '1';
  signal cfg      : t_config  := CFGS(0);
  -- runtime delay = size/radix; wraps to 0 when it equals 2**width (the DUT's
  -- modular compares handle the wrapped code)
  signal cfg_delay : std_logic_vector(clogb2(get_delay_cnt(CFGS)) - 1 downto 0) := (others => '0');
  signal i_sample : t_cmplx   := C_ZERO;
  signal o_sample : t_cmplx;
  signal done     : boolean   := false;

  function to_fx(code : integer) return sfixed is
  begin
    return to_sfixed(std_logic_vector(to_signed(code, c_fxp_word_width)),
                     c_fxp_int_width - 1, -c_fxp_frac_width);
  end function;

  function code_slv(code : integer) return t_word is
  begin
    return std_logic_vector(to_signed(code, c_fxp_word_width));
  end function;

  function slv_image(w : t_word) return string is
  begin
    if is_x(w) then
      return "0x" & to_hstring(w) & " (metavalue)";
    end if;
    return integer'image(to_integer(signed(w)));
  end function;

begin

  dut : entity work.mr_fft_stage
    generic map (G_CAPABILITY => 0, G_CONFIGS => CFGS)
    port map (
      i_clk    => clk,
      i_reset  => reset,
      i_config => cfg,
      i_config_delay => cfg_delay,
      i_sample => i_sample,
      o_sample => o_sample);

  clk <= not clk after CLK_PERIOD / 2 when not done else '0';

  check : process
    variable cap_re, cap_im : t_cap_arr;
    variable n_in, n_exp, vstart, in_ofs, exp_ofs, n_cycles : integer;
    variable errs, cfg_best_errs, cfg_best_lat : integer;
    variable exp_re, exp_im : t_word;
    variable msgs : integer;
    variable pass_all : boolean := true;
  begin
    for c in 0 to NUM_CFGS - 1 loop
      n_in     := (CFG_IN_OFS(c + 1) - CFG_IN_OFS(c)) / 2;
      n_exp    := (CFG_EXP_OFS(c + 1) - CFG_EXP_OFS(c)) / 2;
      vstart   := CFG_VALID_START(c);
      in_ofs   := CFG_IN_OFS(c);
      exp_ofs  := CFG_EXP_OFS(c);
      n_cycles := n_in + C_MAX_LAT + 2;

      -- reset the stage with the new config applied
      reset <= '1';
      cfg   <= (radix => CFG_RADIX(c), size => CFG_SIZE(c));
      cfg_delay <= std_logic_vector(to_unsigned(
          (CFG_SIZE(c) / CFG_RADIX(c)) mod 2**cfg_delay'length, cfg_delay'length));
      i_sample <= C_ZERO;
      for i in 0 to 3 loop
        wait until rising_edge(clk);
      end loop;

      -- cycle k: drive input k just after the rising edge that starts it,
      -- capture o_sample at the falling edge (datapath settled)
      for k in 0 to n_cycles - 1 loop
        wait until rising_edge(clk);
        if k = 0 then
          reset <= '0';
        end if;
        if k < n_in then
          i_sample.re <= to_fx(IN_CODES(in_ofs + 2 * k));
          i_sample.im <= to_fx(IN_CODES(in_ofs + 2 * k + 1));
        else
          i_sample <= C_ZERO;
        end if;
        wait until falling_edge(clk);
        cap_re(k) := to_slv(o_sample.re);
        cap_im(k) := to_slv(o_sample.im);
      end loop;

      -- latency-alignment search: a correct DUT matches at exactly one offset
      cfg_best_errs := integer'high;
      cfg_best_lat  := -1;
      for lat in 0 to C_MAX_LAT loop
        errs := 0;
        for k in 0 to n_exp - 1 loop
          exp_re := code_slv(EXP_CODES(exp_ofs + 2 * k));
          exp_im := code_slv(EXP_CODES(exp_ofs + 2 * k + 1));
          if cap_re(vstart + k + lat) /= exp_re or
             cap_im(vstart + k + lat) /= exp_im then
            errs := errs + 1;
          end if;
        end loop;
        if errs < cfg_best_errs then
          cfg_best_errs := errs;
          cfg_best_lat  := lat;
        end if;
        exit when errs = 0;
      end loop;

      if cfg_best_errs = 0 then
        report "config radix=" & integer'image(CFG_RADIX(c)) &
               " N=" & integer'image(CFG_SIZE(c)) &
               ": PASS -- " & integer'image(n_exp) &
               " samples match at latency " & integer'image(cfg_best_lat)
          severity note;
      else
        pass_all := false;
        report "config radix=" & integer'image(CFG_RADIX(c)) &
               " N=" & integer'image(CFG_SIZE(c)) &
               ": FAIL -- best offset " & integer'image(cfg_best_lat) &
               " still has " & integer'image(cfg_best_errs) & "/" &
               integer'image(n_exp) & " sample mismatches"
          severity error;
        -- dump the first few mismatches at the best offset
        msgs := 0;
        for k in 0 to n_exp - 1 loop
          exp_re := code_slv(EXP_CODES(exp_ofs + 2 * k));
          exp_im := code_slv(EXP_CODES(exp_ofs + 2 * k + 1));
          if cap_re(vstart + k + cfg_best_lat) /= exp_re or
             cap_im(vstart + k + cfg_best_lat) /= exp_im then
            report "  out[" & integer'image(k) & "] (cycle " &
                   integer'image(vstart + k + cfg_best_lat) & ") got (" &
                   slv_image(cap_re(vstart + k + cfg_best_lat)) & "," &
                   slv_image(cap_im(vstart + k + cfg_best_lat)) & ") exp (" &
                   integer'image(EXP_CODES(exp_ofs + 2 * k)) & "," &
                   integer'image(EXP_CODES(exp_ofs + 2 * k + 1)) & ")"
              severity error;
            msgs := msgs + 1;
            exit when msgs = C_MAX_MSG;
          end if;
        end loop;
      end if;
    end loop;

    if pass_all then
      report "TB PASS -- mr_fft_stage (cap0) matches the Python golden model for all configs"
        severity note;
    else
      report "TB FAIL -- mr_fft_stage (cap0) does not match the Python golden model"
        severity failure;
    end if;
    done <= true;
    wait;
  end process check;

end architecture sim;
