library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

library work;
use work.mr_fft_pkg.all;
use work.preadder_vectors_pkg.all;   -- generated by model/preadder_ref.py

-- Self-checking preadder TB driven by generated golden vectors.
-- Regenerate vectors:  python model/preadder_ref.py
-- All three G_CAPABILITY variants are instantiated on shared inputs; each
-- vector is checked against the DUT matching its cap field, comparing raw
-- two's-complement integer codes so any mismatch is a real bit difference.
entity tb_mr_fft_preadder_gen is end entity;

architecture sim of tb_mr_fft_preadder_gen is
	constant C_ZERO : t_cmplx := (re => (others => '0'), im => (others => '0'));

	signal x0, x1, x2, x3, x4 : t_cmplx := C_ZERO;
	signal s0 : std_logic_vector(1 downto 0) := "00";
	signal s1 : std_logic := '0';

	type t_cmplx_arr5 is array (0 to 4) of t_cmplx;
	signal y_g2, y_g1, y_g0 : t_cmplx_arr5;

	function to_fx(code : integer) return sfixed is
	begin
		return to_sfixed(std_logic_vector(to_signed(code, c_fxp_int_width + c_fxp_frac_width)),
		                 c_fxp_int_width - 1, -c_fxp_frac_width);
	end function;

	function code_of(arg : sfixed) return integer is
	begin
		return to_integer(signed(to_slv(arg)));
	end function;
begin

	dut_g2 : entity work.mr_fft_preadder
		generic map (G_CAPABILITY => 2)
		port map (i_clk => '0',
		          i_x0 => x0, i_x1 => x1, i_x2 => x2, i_x3 => x3, i_x4 => x4,
		          i_s0 => s0, i_s1 => s1,
		          o_X0 => y_g2(0), o_X1 => y_g2(1), o_X2 => y_g2(2),
		          o_X3 => y_g2(3), o_X4 => y_g2(4));

	dut_g1 : entity work.mr_fft_preadder
		generic map (G_CAPABILITY => 1)
		port map (i_clk => '0',
		          i_x0 => x0, i_x1 => x1, i_x2 => x2, i_x3 => x3, i_x4 => x4,
		          i_s0 => s0, i_s1 => s1,
		          o_X0 => y_g1(0), o_X1 => y_g1(1), o_X2 => y_g1(2),
		          o_X3 => y_g1(3), o_X4 => y_g1(4));

	dut_g0 : entity work.mr_fft_preadder
		generic map (G_CAPABILITY => 0)
		port map (i_clk => '0',
		          i_x0 => x0, i_x1 => x1, i_x2 => x2, i_x3 => x3, i_x4 => x4,
		          i_s0 => s0, i_s1 => s1,
		          o_X0 => y_g0(0), o_X1 => y_g0(1), o_X2 => y_g0(2),
		          o_X3 => y_g0(3), o_X4 => y_g0(4));

	check : process
		variable errs : integer := 0;
		variable y    : t_cmplx_arr5;
		variable got_re, got_im : integer;

		procedure check_const(name : string; got, exp : integer) is
		begin
			if got /= exp then
				report "FAIL const " & name & " got " & integer'image(got) &
				       " exp " & integer'image(exp) severity error;
				errs := errs + 1;
			end if;
		end procedure;
	begin
		-- The k-constants first: a 1-LSB constant mismatch fails every
		-- downstream multiply vector, so pinpoint it here.
		check_const("k2.re", code_of(c_k2.re), EXP_K2_RE);
		check_const("k3.im", code_of(c_k3.im), EXP_K3_IM);
		check_const("k4.im", code_of(c_k4.im), EXP_K4_IM);
		check_const("k5.im", code_of(c_k5.im), EXP_K5_IM);
		check_const("k6.re", code_of(c_k6.re), EXP_K6_RE);

		for i in TESTS'range loop
			x0.re <= to_fx(TESTS(i).x(0));  x0.im <= to_fx(TESTS(i).x(1));
			x1.re <= to_fx(TESTS(i).x(2));  x1.im <= to_fx(TESTS(i).x(3));
			x2.re <= to_fx(TESTS(i).x(4));  x2.im <= to_fx(TESTS(i).x(5));
			x3.re <= to_fx(TESTS(i).x(6));  x3.im <= to_fx(TESTS(i).x(7));
			x4.re <= to_fx(TESTS(i).x(8));  x4.im <= to_fx(TESTS(i).x(9));
			s0 <= std_logic_vector(to_unsigned(TESTS(i).s0, 2));
			s1 <= '1' when TESTS(i).s1 = 1 else '0';
			wait for 1 ns;

			case TESTS(i).cap is
				when 2      => y := y_g2;
				when 1      => y := y_g1;
				when others => y := y_g0;
			end case;

			for j in 0 to TESTS(i).nout - 1 loop
				got_re := code_of(y(j).re);
				got_im := code_of(y(j).im);
				if got_re /= TESTS(i).e(2*j) or got_im /= TESTS(i).e(2*j + 1) then
					report "FAIL test " & integer'image(i) &
					       " cap=" & integer'image(TESTS(i).cap) &
					       " s0=" & integer'image(TESTS(i).s0) &
					       " s1=" & integer'image(TESTS(i).s1) &
					       " X" & integer'image(j) &
					       " got (" & integer'image(got_re) & "," & integer'image(got_im) &
					       ") exp (" & integer'image(TESTS(i).e(2*j)) & "," &
					       integer'image(TESTS(i).e(2*j + 1)) & ")"
						severity error;
					errs := errs + 1;
				end if;
			end loop;
		end loop;

		if errs = 0 then
			report "TB PASS -- " & integer'image(TESTS'length) &
			       " preadder vectors match the Python golden model" severity note;
		else
			report "TB FAIL -- " & integer'image(errs) & " mismatches" severity failure;
		end if;
		wait;
	end process check;

end architecture sim;
