library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;
use work.mr_fft_pkg.all;
use work.twiddle_pkg.all;
use work.twiddle_vectors_pkg.all;    -- generated by model/twiddle_rom_ref.py

-- Self-checking twiddle_rom TB driven by generated golden vectors.
-- Regenerate vectors:
--   python model/twiddle_rom_ref.py --int 2 --frac 16 \
--     --configs 5:300,3:243,2:3072,2:12,2:8,3:12,5:20,2:2
entity tb_twiddle_rom_gen is end entity;

architecture sim of tb_twiddle_rom_gen is
    signal clk  : std_logic := '0';
    signal sel  : unsigned(SEL_WIDTH-1 downto 0) := (others => '0');
    signal k    : unsigned(K_WIDTH-1 downto 0)   := (others => '0');
    signal tw   : t_cmplx_twiddle;
    signal done : boolean := false;
    signal errs : integer := 0;
begin
    dut : entity work.twiddle_rom
        generic map (CONFIGS => CFGS, SEL_WIDTH => SEL_WIDTH, K_WIDTH => K_WIDTH, REGISTERED => true)
        port map (i_clk => clk,
                  i_config_sel => std_logic_vector(sel),
                  i_k          => std_logic_vector(k),
                  o_twiddle    => tw);

    clk <= not clk after 5 ns when not done else '0';

    process
        variable gre, gim : integer;
    begin
        for i in TESTS'range loop
            sel <= to_unsigned(TESTS(i).sel, SEL_WIDTH);
            k   <= to_unsigned(TESTS(i).k,   K_WIDTH);
            -- params register (sel is quasi-static in the stage, not here)
            -- + fold register + ROM read + margin
            -- params reg + fold reg + addr reg + read + margin (sel changes
            -- per vector here; in the stage config_sel is quasi-static)
            wait until rising_edge(clk); wait until rising_edge(clk);
            wait until rising_edge(clk); wait until rising_edge(clk);
            wait until rising_edge(clk); wait until rising_edge(clk);
            gre := to_integer(signed(to_slv(tw.re)));
            gim := to_integer(signed(to_slv(tw.im)));
            if gre /= TESTS(i).re or gim /= TESTS(i).im then
                report "FAIL sel=" & integer'image(TESTS(i).sel) &
                       " k=" & integer'image(TESTS(i).k) &
                       " got (" & integer'image(gre) & "," & integer'image(gim) &
                       ") exp (" & integer'image(TESTS(i).re) & "," & integer'image(TESTS(i).im) & ")"
                    severity error;
                errs <= errs + 1;
            end if;
        end loop;

        if errs = 0 then
            report "TB PASS -- " & integer'image(TESTS'length) &
                   " twiddle vectors match the Python golden model" severity note;
        else
            report "TB FAIL -- " & integer'image(errs) & " mismatches" severity failure;
        end if;
        done <= true;
        wait;
    end process;
end architecture;
